In [1]:
# Re-définir les matrices d'exemple
import numpy as np

# Matrice d'exemple (image 5x5)
image_example = np.array([
    [10, 20, 30, 40, 50],
    [15, 25, 35, 45, 55],
    [20, 30, 40, 50, 60],
    [25, 35, 45, 55, 65],
    [30, 40, 50, 60, 70]
])

# Noyau simple 3x3 pour convolution
kernel = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1]
]) / 9  # Moyenne (blur)

# 1. Mettre à zéro les bords
padded_zero = np.pad(image_example, pad_width=1, mode='constant', constant_values=0)

# 2. Convolution partielle (ignore les bords en sortie, effectue uniquement sur le centre)
center_only = image_example[1:-1, 1:-1]

# 3. Miroir de l'image
padded_mirror = np.pad(image_example, pad_width=1, mode='reflect')

# 4. Duplication
padded_duplicate = np.pad(image_example, pad_width=1, mode='edge')

padded_zero, padded_mirror, padded_duplicate


(array([[ 0,  0,  0,  0,  0,  0,  0],
        [ 0, 10, 20, 30, 40, 50,  0],
        [ 0, 15, 25, 35, 45, 55,  0],
        [ 0, 20, 30, 40, 50, 60,  0],
        [ 0, 25, 35, 45, 55, 65,  0],
        [ 0, 30, 40, 50, 60, 70,  0],
        [ 0,  0,  0,  0,  0,  0,  0]]),
 array([[25, 15, 25, 35, 45, 55, 45],
        [20, 10, 20, 30, 40, 50, 40],
        [25, 15, 25, 35, 45, 55, 45],
        [30, 20, 30, 40, 50, 60, 50],
        [35, 25, 35, 45, 55, 65, 55],
        [40, 30, 40, 50, 60, 70, 60],
        [35, 25, 35, 45, 55, 65, 55]]),
 array([[10, 10, 20, 30, 40, 50, 50],
        [10, 10, 20, 30, 40, 50, 50],
        [15, 15, 25, 35, 45, 55, 55],
        [20, 20, 30, 40, 50, 60, 60],
        [25, 25, 35, 45, 55, 65, 65],
        [30, 30, 40, 50, 60, 70, 70],
        [30, 30, 40, 50, 60, 70, 70]]))