### **Filtre Gaussien & Laplacien**

* Gaussien : Floute une image pour réduire le bruit et lisser les transitions.
* Gradient (Sobel) : Détecte les contours en mesurant le taux de changement de l'intensité des pixels.
* Laplacien : Détecte les contours en mesurant la deuxième dérivée de l'intensité, ce qui met en évidence les zones de variation rapide sans considération de direction.

*Loaading image*

In [1]:
try:
    import cv2
except Exception as  e:
    print(f"erreur {e}")
import numpy as np
import math

In [53]:
image = cv2.imread('assets/img3.png', cv2.IMREAD_GRAYSCALE)

*Filtre de Gausse*

In [3]:
# flou
kernel_Gausse = np.array([[1,2,1],[2,4,2],[1,2,1]])/16

*Filtre de Laplacien*

In [5]:

kernel_Lap = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]])

*Filtre de rehaussement*

In [6]:
Kernel_rehaussement = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])

*Inverser la valeur de rehaussement Kernel*

In [7]:
Kernel_rehaussement1 = np.array([[0,1,0],[1,5,1],[0,1,0]])
Kernel_rehaussement2 = np.array([[0,1,0],[1,3,1],[0,1,0]])

In [8]:
# kernel_grad = np.array([[2, 2, -2], [2, 0, -2], [0, -2, -2]])  -> gradient de x et de y 

In [9]:
imgRes = cv2.filter2D(image ,-1, kernel_Gausse)

In [10]:
imgRes = cv2.filter2D(image ,-1, Kernel_rehaussement)
cv2.normalize(imgRes , imgRes , 0 , 255 , cv2.NORM_MINMAX)

array([[255, 253, 224, ..., 254, 254, 254],
       [206, 246, 255, ..., 254, 254, 254],
       [255, 255, 255, ..., 254, 254, 254],
       ...,
       [255, 236, 255, ..., 255, 255, 255],
       [255, 241, 255, ..., 255, 255, 255],
       [255, 246, 255, ..., 255, 255, 255]], dtype=uint8)

In [11]:
imgRes = cv2.filter2D(image ,-1, kernel_Lap)
cv2.normalize(imgRes , imgRes , 0 , 255 , cv2.NORM_MINMAX)

array([[28,  2,  0, ...,  0,  0,  0],
       [ 0,  0, 18, ...,  0,  0,  0],
       [14,  5, 48, ...,  0,  0,  0],
       ...,
       [ 6,  0, 16, ...,  0,  0,  0],
       [10,  0,  5, ...,  0,  0,  0],
       [ 6,  0,  4, ...,  0,  0,  0]], dtype=uint8)

In [ ]:
imgRes = cv2.filter2D(image ,-1, kernel_grad)
cv2.normalize(imgRes , imgRes , 0 , 255 , cv2.NORM_MINMAX)

*Guasse Fonction*

In [54]:
def gausse ( x , y , sigma ):
    part1 = 1/(2*math.pi *pow(sigma,2))
    part2 = -(x*x + y*y)/(2*pow(sigma, 2))
    return part1 * math.pow(math.e , part2)

def print_gausse (sigma = 1.4 , vois_mat = 3):
    matrice_gausse = np.zeros((3,3))
    vois = int(vois_mat/2)
    x ,y = 0,0
    som = 0.0
    for i in range(-vois, vois+1):
        for j in range(-vois, vois+1):
            val = gausse(i , j , sigma)
            val = round(val,185 )
            matrice_gausse[i+vois][j+vois]=val
            print('{:02.2f}'.format(val),'\t', end = "")
            som+=val
        print('')
    print(f"som : {som}")
    return matrice_gausse 
        
            

In [55]:
matrice_gausse = print_gausse (sigma = 1.4 , vois_mat = 3)

0.05 	0.06 	0.05 	
0.06 	0.08 	0.06 	
0.05 	0.06 	0.05 	
som : 0.5278781222004043


In [56]:
matrice_gausse

array([[0.04875119, 0.06291796, 0.04875119],
       [0.06291796, 0.0812015 , 0.06291796],
       [0.04875119, 0.06291796, 0.04875119]])

In [57]:
imgRes = cv2.filter2D(image ,-1, matrice_gausse)
cv2.normalize(imgRes , imgRes , 0 , 255 , cv2.NORM_MINMAX)

array([[249, 249, 251, ..., 253, 253, 253],
       [251, 251, 247, ..., 253, 253, 253],
       [251, 253, 242, ..., 253, 253, 253],
       ...,
       [249, 251, 247, ..., 255, 255, 255],
       [251, 251, 251, ..., 255, 255, 255],
       [251, 251, 253, ..., 255, 255, 255]], dtype=uint8)

*Affichage*

In [58]:
cv2.imshow('Image source', image)
cv2.imshow('Image Res', imgRes)


cv2.waitKey(0)
cv2.destroyAllWindows()