## Partie1

In [1]:
import cv2
import numpy as np

# Define color range
lo = np.array([95, 80, 60])
hi = np.array([115, 255, 255])

def detect_inrange(image):
    points = []
    # Convert to HSV
    hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    # Threshold the HSV image
    
    # cv2.inRange: Crée un masque binaire où les pixels dans la plage lo et hi sont blancs (255) et les autres noirs (0). Cela sert à isoler les pixels de la couleur cible.
    mask = cv2.inRange(hsv_image, lo, hi)
    
    # Apply morphological operations : 
    # cv2.MORPH_CLOSE: Ferme les petits trous dans les zones blanches.
    # cv2.MORPH_OPEN: Élimine les petites régions blanches bruitées.

    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))  # Define the kernel
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)  # Close small gaps
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)   # Remove small noise

    # Find contours
    # cv2.findContours: Trouve les contours des régions blanches dans le masque.
    # cv2.contourArea: Trie les contours par aire (du plus grand au plus petit).
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    contours = sorted(contours, key=lambda x: cv2.contourArea(x), reverse=True)
    
    for contour in contours:
        # cv2.minEnclosingCircle: Trouve le cercle le plus petit englobant un contour.
        # points: Liste des cercles détectés avec leur centre (x, y), rayon et aire.
        ((x, y), radius) = cv2.minEnclosingCircle(contour)
        points.append(np.array([int(x), int(y),; int(radius), int(cv2.contourArea(contour))]))
    
    # mask: Image binaire après filtrage.
    # contours:Contours trouvés.
    # points: Liste des cercles détectés
    return mask, contours, points

# Open video capture
VideoCap = cv2.VideoCapture(2)

while True:
    ret, frame = VideoCap.read()
    if not ret:
        break

    frame = cv2.flip(frame, 1)  # Flip frame horizontally
    mask, contours, points = detect_inrange(frame)

    # Draw the contours on the original frame
    cv2.drawContours(frame, contours, -1, (0, 255, 0), 2)  # Green color, thickness=2

    # Draw a static green circle for testing
    cv2.circle(frame, (100, 100), 20, (255, 0, 0), 2)
    print(frame[100, 100])  # Display pixel value at a specific point

    if len(points) > 0:
        # Draw a red circle for the largest detected object
        x, y, radius, _ = points[0]
        cv2.circle(frame, (x, y), radius, (0, 0, 255), 2)

    if mask is not None:
        cv2.imshow("mask", mask)  # Display the mask

    cv2.imshow('image', frame)  # Display the frame with contours
    if cv2.waitKey(10) & 0xFF == ord("q"):
        break

# Release video capture and close windows
VideoCap.release()
cv2.destroyAllWindows()

[147 176 190]
[146 175 187]
[140 171 185]
[137 174 190]
[136 175 195]
[137 178 197]
[146 179 196]
[141 171 186]
[64 71 67]
[115 110  93]
[127 115  94]
[127 115  94]
[134 120  96]
[136 122  96]
[138 125 100]
[138 125 100]
[139 126 101]
[138 126 101]
[138 126 101]
[137 124 100]
[135 122 102]
[135 122 100]
[135 122 100]
[136 123 101]
[136 123 101]
[137 126 102]
[137 126 102]
[138 127 103]
[136 127 103]
[138 125 101]
[140 127 101]
[140 127 101]
[140 127 101]
[140 127 101]
[136 128 103]
[137 129 102]
[137 129 102]
[137 128 102]
[139 128 104]
[139 128 103]
[139 128 103]
[140 128 103]
[142 128 102]
[142 128 102]
[143 129 103]
[143 129 103]
[144 130 104]
[144 130 104]
[144 130 104]
[144 130 104]
[137 127 101]
[139 128 101]
[139 128 101]
[143 131 103]
[142 130 103]
[143 130 103]
[143 129 102]
[143 129 100]
[143 129 100]
[143 129 101]
[143 129 101]
[143 129 100]
[145 131 103]
[145 130 102]
[145 131 103]
[143 129 101]
[145 131 103]
[145 131 103]
[142 128  99]
[142 128  99]
[142 128 100]
[  0 255 

## partie2

In [2]:
import cv2
import numpy as np

# Define color range
lo = np.array([95, 80, 60])
hi = np.array([115, 255, 255])

def detect_inrange(image):
    points = []
    # Convert to HSV
    hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    # Threshold the HSV image
    mask = cv2.inRange(hsv_image, lo, hi)
    
    # Apply morphological operations
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))  # Define the kernel
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)  # Close small gaps
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)   # Remove small noise

    # Find contours
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    contours = sorted(contours, key=lambda x: cv2.contourArea(x), reverse=True)
    
    for contour in contours:
        ((x, y), radius) = cv2.minEnclosingCircle(contour)
        points.append(np.array([int(x), int(y), int(radius), int(cv2.contourArea(contour))]))
    
    return mask, contours, points

# Open video capture
VideoCap = cv2.VideoCapture(2)

while True:
    ret, frame = VideoCap.read()
    if not ret:
        break

    frame = cv2.flip(frame, 1)  # Flip frame horizontally
    mask, contours, points = detect_inrange(frame)

    # Draw the contours on the mask
    mask_colored = cv2.cvtColor(mask, cv2.COLOR_GRAY2BGR)  # Convert mask to BGR for drawing
    cv2.drawContours(mask_colored, contours, -1, (0, 255, 0), 2)  # Green color, thickness=2

    if len(points) > 0:
        # Get the largest detected object
        x, y, radius, area = points[0]
        
        # Draw the surface area on the mask
        cv2.putText(mask_colored, f"Area: {area}", (int(x) - 50, int(y) - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)  # Green text

    # Display the mask with area annotations
    cv2.imshow("mask", mask_colored)  # Display the annotated mask

    # Draw a static green circle for testing on the original frame
    cv2.circle(frame, (100, 100), 20, (255, 0, 0), 2)

    if len(points) > 0:
        # Draw a red circle for the largest detected object on the frame
        x, y, radius, _ = points[0]
        cv2.circle(frame, (x, y), radius, (0, 0, 255), 2)

    cv2.imshow('image', frame)  # Display the frame
    if cv2.waitKey(10) & 0xFF == ord("q"):
        break

# Release video capture and close windows
VideoCap.release()
cv2.destroyAllWindows()